// <auto-generated />
namespace IssueTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateIssue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateIssue));
        
        string IMigrationMetadata.Id
        {
            get { return "202009091042233_updateIssue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
